name: CI

on:
  push:
    branches: [ master ] 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
  
    steps:
    - uses: actions/checkout@v4
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: cd js && npm install && npm run build
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        # select a 'version' from https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json
        dotnet-version: 6.0.100
        include-prerelease: true
    - name: build
      run: dotnet build **/*.csproj --configuration CI
    - name: test
      run: dotnet test *Tests --configuration CI
      timeout-minutes: 5
      env:
        WAIT_FOR_STATE_TIMEOUT_SEC: 30
