name: CI

on:
  push:
    branches: [ master, trigger_CI ] 

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.1'
    - name: yarn
      run: cd js/blatex && yarn install && yarn build && cd ..
    - name: npm
      run: cd js && npm install && npm run build && cd ..
    - name: build
      run: dotnet build **/*.csproj --configuration CI
    - name: test
      run: dotnet test *Tests --configuration CI
      timeout-minutes: 5
      env:
        WAIT_FOR_STATE_TIMEOUT_SEC: 30