name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: build
      run: dotnet build **/*.csproj
    - name: test
      run: dotnet test *Tests
    